<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'spec\\' => array($vendorDir . '/sensiolabs/behat-page-object-extension'),
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/reflection/src', $vendorDir . '/phpdocumentor/reflection/tests/unit', $vendorDir . '/phpdocumentor/reflection/tests/mocks', $vendorDir . '/phpdocumentor/graphviz/src', $vendorDir . '/phpdocumentor/graphviz/tests/unit', $vendorDir . '/phpdocumentor/fileset/src', $vendorDir . '/phpdocumentor/fileset/tests/unit', $vendorDir . '/phpdocumentor/phpdocumentor/src', $vendorDir . '/phpdocumentor/phpdocumentor/tests/unit'),
    'WebDriver' => array($vendorDir . '/instaclick/php-webdriver/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'SensioLabs\\Behat\\PageObjectExtension\\' => array($vendorDir . '/sensiolabs/behat-page-object-extension/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src'),
    'PhpCollection' => array($vendorDir . '/phpcollection/phpcollection/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'PHPMD\\' => array($vendorDir . '/phpmd/phpmd/src/main/php'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'KevinGH\\Version' => array($vendorDir . '/kherge/version/src/lib'),
    'JMS\\Serializer' => array($vendorDir . '/jms/serializer/src'),
    'JMS\\' => array($vendorDir . '/jms/parser-lib/src'),
    'Herrera\\Phar\\Update' => array($vendorDir . '/herrera-io/phar-update/src/lib'),
    'Herrera\\Json' => array($vendorDir . '/herrera-io/json/src/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Cilex\\Provider\\Console' => array($vendorDir . '/cilex/console-service-provider/src'),
    'Cilex\\Provider' => array($vendorDir . '/phpdocumentor/phpdocumentor/src'),
    'Cilex' => array($vendorDir . '/cilex/cilex/src'),
    'Behat\\YiiExtension' => array($vendorDir . '/behat/yii-extension/src'),
    'Behat\\MinkExtension' => array($vendorDir . '/behat/mink-extension/src'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'Behat\\Behat' => array($vendorDir . '/behat/behat/src'),
);
